baseURL: https://ohmerci.github.io/
languageCode: en-us
title: Moon
theme: PaperMod
defaultContentLanguage: zh
#defaultContentLanguageInSubdir: true

languages:
  zh:
    weight: 1
    title: "æœˆ"
    contentDir: content/zh
    profileMode:
      enabled: true
      title: "ç›ˆå‡¸æœˆ 99%"
      subtitle: "â›… è¯æ ¹ | â˜ï¸ å‰ç¼€ | ðŸŒ™ åŽç¼€ | â­ è¯å…¸"
      buttons:
        - name: æ–‡ç« 
          url: posts
        - name: è¯æ ¹å­—å…¸
          url: https://dictionary.com
    menu:
      main:
        - name: "å½’æ¡£"
          url: archives
          weight: 5
        - name: "æœç´¢"
          url: search/
          weight: 10
        - name: "æ ‡ç­¾"
          url: tags/
          weight: 10
        - name: "åˆ†ç±»"
          url: categories
          weight: 10
        - name: Dictionary
          url: https://dictionary.com

  en:
    weight: 2
    title: PaperMod
    languageName: English
    contentDir: content/en
    menu:
      main:
        - name: Archive
          url: archives
          weight: 10
    homeInfoParams:
      Title: "PaperMod"
      Content: >
          Welcome to demo of hugo's theme PaperMod.

          - **PaperMod** is a simple but fast and responsive theme with useful feature-set that enhances UX.

          - Do give a ðŸŒŸ on Github !

          - PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper).

  fr:
    languageName: FranÃ§ais
    title: FranÃ§ais
    weight: 3
    contentDir: content/fr
    params:
      socialIcons:
    profileMode:
      enabled: true
      title: "j'aime la lune"
      
  ug:
    languageName: Ø¦Û‡ÙŠØºÛ‡Ø±
    languagedirection: rtl
    weight: 4
    title: Ø¦Ø§ÙŠ
    homeInfoParams:
      Title: Ø¦Û‡ÙŠØºÛ‡Ø±
      Content: Ù…Û•Ù† Ø´Ù‰Ù†Ø¬Ø§Ú­Ù†Ù‰ ÙŠØ§Ø®Ø´Ù‰ ÙƒÛ†Ø±Ù‰Ù…Û•Ù†
    menu:
      main:
      - name: "ã€€ã€€ã€€ã€€ã€€"
        url: ../fr/archives/
    params:
      profileMode:
        enabled: false
  
outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  
  env: production
  ShowShareButtons: true
  #ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowRssButtonInSectionTermList: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  #ShowFullTextinRSS: true
  ShowToc: true

  ShareButtons: ["telegram", "twitter"]

  socialIcons:
    - name: instagram
      url: "https://instagram.com/"
    - name: github
      url: "https://github.com/"
    - name: twitter
      url: "https://twitter.com/"
  
  profileMode:
    enabled: false

markup:
  goldmark:
    renderer:
      unsafe: true
  # highlight:
  #   noClasses: false
