baseURL: https://ohmerci.github.io/
languageCode: en-us
title: oh merci
theme: PaperMod
defaultContentLanguage: zh
#defaultContentLanguageInSubdir: true

languages:
  zh:
    weight: 1
    title: "oh merci"
    contentDir: content/zh
    profileMode:
      enabled: true
      # imageUrl: "https://raw.githubusercontent.com/ohmerci/For-Picgo/main/img/The-Moon-Rotates.svg"
      # imageTitle: "å›¾æ ‡-iconfont/é‡‘è§’å¤§çŽ‹"
      # imageWidth: 300
      # imageHeight: 300
      title: "å­¦ä¹ è®°å½•blog"
      subtitle: "æˆ‘å–œæ¬¢çš„åŠ¨æ¼«:n"
      buttons:
        - name: "â›… è¯æ ¹"
          url: posts/root
        - name: "â˜ï¸ å‰ç¼€"
          url: posts/prefix
        - name: "ðŸŒ™ åŽç¼€"
          url: posts/suffix
        - name: "ðŸ“– è¯æ ¹å­—å…¸"
          url: https://dictionary.com
    menu:
      main:
        - name: "å½’æ¡£"
          url: archives
          weight: 5
        - name: "æœç´¢"
          url: search/
          weight: 10
        - name: "æ ‡ç­¾"
          url: tags/
          weight: 10
        - name: "åˆ†ç±»"
          url: categories
          weight: 10
        - name: Dictionary
          url: https://dictionary.com

  en:
    weight: 2
    languageName: English
    contentDir: content/en
    menu:
      main:
        - name: Archive
          url: archives
          weight: 10
    homeInfoParams:
      Title: "PaperMod"
      Content: >
          Welcome to demo of hugo's theme PaperMod.

          - **PaperMod** is a simple but fast and responsive theme with useful feature-set that enhances UX.

          - Do give a ðŸŒŸ on Github !

          - PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper).

  fr:
    languageName: FranÃ§ais
    title: oh merci
    weight: 3
    contentDir: content/fr
    params:
      socialIcons:
    profileMode:
      enabled: true
      title: "j'aime la lune"
      
  ug:
    languageName: Ø¦Û‡ÙŠØºÛ‡Ø±
    languagedirection: rtl
    contentDir: content/ug
    weight: 4
    title: Ø¦Ø§ÙŠ
    homeInfoParams:
      Title: Ø¦Û‡ÙŠØºÛ‡Ø±
      Content: Ù…Û•Ù† Ø´Ù‰Ù†Ø¬Ø§Ú­Ù†Ù‰ ÙŠØ§Ø®Ø´Ù‰ ÙƒÛ†Ø±Ù‰Ù…Û•Ù†
    menu:
      main:
      - name: "ã€€ã€€ã€€ã€€ã€€"
        url: ../fr/archives/
    params:
      profileMode:
        enabled: false
  
outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  
  env: production
  #ShowShareButtons: true
  #ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowRssButtonInSectionTermList: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  #ShowFullTextinRSS: true
  ShowToc: true

  ShareButtons: ["telegram", "twitter"]

  socialIcons:
    - name: instagram
      url: "https://instagram.com/oh_merciii"
    - name: github
      url: "https://github.com/ohmerci"
    - name: telegram
      url: "https://t.me/ohmerci"
  
  profileMode:
    enabled: false

    assets:
      favicon: "https://raw.githubusercontent.com/ohmerci/For-Picgo/main/img/favicon.ico"
      favicon16x16: "https://raw.githubusercontent.com/ohmerci/For-Picgo/main/img/favicon-16x16.png"
      favicon32x32: "https://raw.githubusercontent.com/ohmerci/For-Picgo/main/img/favicon-32x21.png"
      apple_touch_icon: "https://raw.githubusercontent.com/ohmerci/For-Picgo/main/img/apple-touch-icon.png"
      safari_pinned_tab: "https://raw.githubusercontent.com/ohmerci/For-Picgo/main/img/apple-touch-icon.png"

markup:
  goldmark:
    renderer:
      unsafe: true
  # highlight:
  #   noClasses: false
